  
let initialState = {
    partnersList: [
        {
            id: 1,
            pid: 159234,
            name: 'Frozen yoghurt',
            img: 'https://blog.matcharesident.com/wp-content/uploads/2019/07/iStock-944453634-750x450.jpg',
            url: 'https://www.google.com/',
            flag: 6.0,
            sso: 'WIDGET_SSO',
            partnerIsActive: false,
            sendWelcomeEmail: true,
            sendWelcomeEmailSSO: true,
            logWidgetView: true,
            hasJointAccounts: false,
            migrationViewEnabled: false,
            skipConfirmIdentity: true,
            skipAuth: false,
            ssoTrafficMonitoring: false
        },
        {
            id: 2,
            pid: 159234,
            name: 'Frozen yoghurt',
            img: 'https://blog.matcharesident.com/wp-content/uploads/2019/07/iStock-944453634-750x450.jpg',
            url: 'https://www.google.com/',
            flag: 6.0,
            sso: 'WIDGET_SSO',
            partnerIsActive: true,
            sendWelcomeEmail: true,
            sendWelcomeEmailSSO: true,
            logWidgetView: true,
            hasJointAccounts: false,
            migrationViewEnabled: false,
            skipConfirmIdentity: true,
            skipAuth: false,
            ssoTrafficMonitoring: false
        },
        {
            id: 3,
            pid: 159234,
            name: 'Frozen yoghurt',
            img: 'https://blog.matcharesident.com/wp-content/uploads/2019/07/iStock-944453634-750x450.jpg',
            url: 'https://www.google.com/',
            flag: 6.0,
            sso: 'WIDGET_SSO',
            partnerIsActive: true,
            sendWelcomeEmail: true,
            sendWelcomeEmailSSO: true,
            logWidgetView: true,
            hasJointAccounts: false,
            migrationViewEnabled: false,
            skipConfirmIdentity: true,
            skipAuth: false,
            ssoTrafficMonitoring: false
        },
        {
            id: 4,
            pid: 159234,
            name: 'Frozen yoghurt',
            img: 'https://blog.matcharesident.com/wp-content/uploads/2019/07/iStock-944453634-750x450.jpg',
            url: 'https://www.google.com/',
            flag: 6.0,
            sso: 'WIDGET_SSO',
            partnerIsActive: true,
            sendWelcomeEmail: true,
            sendWelcomeEmailSSO: true,
            logWidgetView: true,
            hasJointAccounts: false,
            migrationViewEnabled: false,
            skipConfirmIdentity: true,
            skipAuth: false,
            ssoTrafficMonitoring: false
        },
        {
            id: 5,
            pid: 159234,
            name: 'Frozen yoghurt',
            img: 'https://blog.matcharesident.com/wp-content/uploads/2019/07/iStock-944453634-750x450.jpg',
            url: 'https://www.google.com/',
            flag: 6.0,
            sso: 'WIDGET_SSO',
            partnerIsActive: true,
            sendWelcomeEmail: true,
            sendWelcomeEmailSSO: true,
            logWidgetView: true,
            hasJointAccounts: false,
            migrationViewEnabled: false,
            skipConfirmIdentity: true,
            skipAuth: false,
            ssoTrafficMonitoring: false
        },
        {
            id: 6,
            pid: 159234,
            name: 'Frozen yoghurt',
            img: 'https://blog.matcharesident.com/wp-content/uploads/2019/07/iStock-944453634-750x450.jpg',
            url: 'https://www.google.com/',
            flag: 6.0,
            sso: 'WIDGET_SSO',
            partnerIsActive: true,
            sendWelcomeEmail: true,
            sendWelcomeEmailSSO: true,
            logWidgetView: true,
            hasJointAccounts: false,
            migrationViewEnabled: false,
            skipConfirmIdentity: true,
            skipAuth: false,
            ssoTrafficMonitoring: false
        },
        {
            id: 7,
            pid: 159234,
            name: 'Frozen yoghurt',
            img: 'https://blog.matcharesident.com/wp-content/uploads/2019/07/iStock-944453634-750x450.jpg',
            url: 'https://www.google.com/',
            flag: 6.0,
            sso: 'WIDGET_SSO',
            partnerIsActive: true,
            sendWelcomeEmail: true,
            sendWelcomeEmailSSO: true,
            logWidgetView: true,
            hasJointAccounts: false,
            migrationViewEnabled: false,
            skipConfirmIdentity: true,
            skipAuth: false,
            ssoTrafficMonitoring: false
        },
        {
            id: 8,
            pid: 159234,
            name: 'Frozen yoghurt',
            img: 'https://blog.matcharesident.com/wp-content/uploads/2019/07/iStock-944453634-750x450.jpg',
            url: 'https://www.google.com/',
            flag: 6.0,
            sso: 'WIDGET_SSO',
            partnerIsActive: true,
            sendWelcomeEmail: true,
            sendWelcomeEmailSSO: true,
            logWidgetView: true,
            hasJointAccounts: false,
            migrationViewEnabled: false,
            skipConfirmIdentity: true,
            skipAuth: false,
            ssoTrafficMonitoring: false
        },
        {
            id: 9,
            pid: 159234,
            name: 'Frozen yoghurt',
            img: 'https://blog.matcharesident.com/wp-content/uploads/2019/07/iStock-944453634-750x450.jpg',
            url: 'https://www.google.com/',
            flag: 6.0,
            sso: 'WIDGET_SSO',
            partnerIsActive: true,
            sendWelcomeEmail: true,
            sendWelcomeEmailSSO: true,
            logWidgetView: true,
            hasJointAccounts: false,
            migrationViewEnabled: false,
            skipConfirmIdentity: true,
            skipAuth: false,
            ssoTrafficMonitoring: false
        },
        {
            id: 10,
            pid: 159234,
            name: 'Frozen yoghurt',
            img: 'https://blog.matcharesident.com/wp-content/uploads/2019/07/iStock-944453634-750x450.jpg',
            url: 'https://www.google.com/',
            flag: 6.0,
            sso: 'WIDGET_SSO',
            partnerIsActive: true,
            sendWelcomeEmail: true,
            sendWelcomeEmailSSO: true,
            logWidgetView: true,
            hasJointAccounts: false,
            migrationViewEnabled: false,
            skipConfirmIdentity: true,
            skipAuth: false,
            ssoTrafficMonitoring: false
        },
        {
            id: 11,
            pid: 159234,
            name: 'Frozen yoghurt',
            img: 'https://blog.matcharesident.com/wp-content/uploads/2019/07/iStock-944453634-750x450.jpg',
            url: 'https://www.google.com/',
            flag: 6.0,
            sso: 'WIDGET_SSO',
            partnerIsActive: true,
            sendWelcomeEmail: true,
            sendWelcomeEmailSSO: true,
            logWidgetView: true,
            hasJointAccounts: false,
            migrationViewEnabled: false,
            skipConfirmIdentity: true,
            skipAuth: false,
            ssoTrafficMonitoring: false
        },
        {
            id: 12,
            pid: 159234,
            name: 'Frozen yoghurt',
            img: 'https://blog.matcharesident.com/wp-content/uploads/2019/07/iStock-944453634-750x450.jpg',
            url: 'https://www.google.com/',
            flag: 6.0,
            sso: 'WIDGET_SSO',
            partnerIsActive: true,
            sendWelcomeEmail: true,
            sendWelcomeEmailSSO: true,
            logWidgetView: true,
            hasJointAccounts: false,
            migrationViewEnabled: false,
            skipConfirmIdentity: true,
            skipAuth: false,
            ssoTrafficMonitoring: false
        },
        {
            id: 13,
            pid: 159234,
            name: 'Frozen yoghurt',
            img: 'https://blog.matcharesident.com/wp-content/uploads/2019/07/iStock-944453634-750x450.jpg',
            url: 'https://www.google.com/',
            flag: 6.0,
            sso: 'WIDGET_SSO',
            partnerIsActive: true,
            sendWelcomeEmail: true,
            sendWelcomeEmailSSO: true,
            logWidgetView: true,
            hasJointAccounts: false,
            migrationViewEnabled: false,
            skipConfirmIdentity: true,
            skipAuth: false,
            ssoTrafficMonitoring: false
        },
        {
            id: 14,
            pid: 159234,
            name: 'Frozen yoghurt',
            img: 'https://blog.matcharesident.com/wp-content/uploads/2019/07/iStock-944453634-750x450.jpg',
            url: 'https://www.google.com/',
            flag: 6.0,
            sso: 'WIDGET_SSO',
            partnerIsActive: true,
            sendWelcomeEmail: true,
            sendWelcomeEmailSSO: true,
            logWidgetView: true,
            hasJointAccounts: false,
            migrationViewEnabled: false,
            skipConfirmIdentity: true,
            skipAuth: false,
            ssoTrafficMonitoring: false
        },
        {
            id: 15,
            pid: 159234,
            name: 'Frozen yoghurt',
            img: 'https://blog.matcharesident.com/wp-content/uploads/2019/07/iStock-944453634-750x450.jpg',
            url: 'https://www.google.com/',
            flag: 6.0,
            sso: 'WIDGET_SSO',
            partnerIsActive: true,
            sendWelcomeEmail: true,
            sendWelcomeEmailSSO: true,
            logWidgetView: true,
            hasJointAccounts: false,
            migrationViewEnabled: false,
            skipConfirmIdentity: true,
            skipAuth: false,
            ssoTrafficMonitoring: false
        },
        {
            id: 16,
            pid: 159234,
            name: 'Frozen yoghurt',
            img: 'https://blog.matcharesident.com/wp-content/uploads/2019/07/iStock-944453634-750x450.jpg',
            url: 'https://www.google.com/',
            flag: 6.0,
            sso: 'WIDGET_SSO',
            partnerIsActive: true,
            sendWelcomeEmail: true,
            sendWelcomeEmailSSO: true,
            logWidgetView: true,
            hasJointAccounts: false,
            migrationViewEnabled: false,
            skipConfirmIdentity: true,
            skipAuth: false,
            ssoTrafficMonitoring: false
        },
        {
            id: 17,
            pid: 159234,
            name: 'Frozen yoghurt',
            img: 'https://blog.matcharesident.com/wp-content/uploads/2019/07/iStock-944453634-750x450.jpg',
            url: 'https://www.google.com/',
            flag: 6.0,
            sso: 'WIDGET_SSO',
            partnerIsActive: true,
            sendWelcomeEmail: true,
            sendWelcomeEmailSSO: true,
            logWidgetView: true,
            hasJointAccounts: false,
            migrationViewEnabled: false,
            skipConfirmIdentity: true,
            skipAuth: false,
            ssoTrafficMonitoring: false
        }
    ],
    partnersArr:[]
};

const partnersReducer = (state = initialState, action) => {
    console.log(state)
	switch (action.type) {
		case 'ADDPARTNER':
			return {
				...state,
				// partnersArr: action.payload
			};
		default:
			return state;
	}
};

export default partnersReducer;